bnb-chain/greenfield-cosmos-sdk

x/gashub/types/params.go
Description
This pr will add gas config for new message type: msgUpdateObjectInfo.
Rationale
Support new message.
Example
NA
Changes
new gas config
=> feat: add gas config for UpdateObjectInfo message

tests/e2e/distribution/suite.go, x/distribution/client/cli/suite_test.go, x/distribution/client/cli/tx.go, x/distribution/client/testutil/helpers.go, x/distribution/simulation/operations.go, x/distribution/types/common_test.go, x/distribution/types/msg.go, x/distribution/types/msg_test.go
This pr migrates the change of:
#108 feat: split commands for withdrawal of rewards and commission 
Due to the EIP712 requirement, only one message can be executed in an single transaction.
- distribution `withdraw-rewards` 
- distribution `withdraw-commission`
* update cli
=> feat: split commands for withdraw rewards and commission due to eip712

client/keys/output.go, client/keys/output_test.go, crypto/keyring/keyring.go
add `bls` key-type to keyring management
support `bls` algorithm to help the validator manage the bls_keys in command lines.
1. add keys
cmd: `./build/simd keys add test --key-type eth_bls --home ./.local --keyring-backend test`
2. show keys
cmd: `./build/simd keys list --home ./.local --keyring-backend test`
3. import keys
cmd: `./build/simd keys import test ./priv.key --home ./.local --keyring-backend test`
* keyring tool
=> feat: add 'bls' key-type to keyring management

math/uint.go, math/uint_test.go
This pr cherry picks https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/114:
+ add Bytes/SetBytes to get big endian format for Uint.
Cherry-pick the previous changes.
N/A
* add Bytes/SetBytes to get big endian format for Uint.
=> feat: add Bytes/SetBytes for Bigendian encoding for Uint

client/keys/add.go, simapp/simd/cmd/testnet.go
This pr is to change the default key algo in cmd.
EthSecp256k1 should be the default algo.
* change default key algo in cmd
=> chore: change default key algo

buf.work.yaml
This pr will fix the issue when generating swagger file int greenfiled:
```
Failure: directory "orm/internal" listed in ../github.com/bnb-chain/greenfield-cosmos-sdk@v0.0.0-20230509083558-18999c4902bf/buf.work.yaml contains no .proto files
```
Fix error when generating swagger file.
N/A
* remove orm directory for buf
=> fix: remove orm directory for buf

tests/e2e/feegrant/suite.go, x/feegrant/client/cli/tx_test.go, x/gov/client/cli/tx.go, x/gov/module.go, x/params/client/cli/tx.go
gov v1beta1 server should be disabled, migrate such change to v47.2. 
would cause user's confusion providing the legacy server
NA
* NA
=> feat: disable gov v1beta1

CHANGELOG.md
This release upgrades cosmos-sdk to v0.47.2.  
This release upgrades the reference cosmos-sdk to v0.47.2. As the cosmos-sdk v0.47.2 is a huge breaking upgrade, 
we decide to cherry-pick the recent contributed commits and apply to the v0.47.2. The commit history previous 
releases are archived and the branch is backed up in the `master_back` branch.
1. The previous keyring is replaced by the new keyring. Please regenerate them, otherwise you will get error.
Other notable changes, please refer to the [changelogs of cosmos-sdk v0.47.2](https://github.com/cosmos/cosmos-sdk/blob/v0.47.1/CHANGELOG.md).
=> release: draft release v0.2.0

CHANGELOG.md
This is a maintenance release.  
* [#214](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/214) chore: fix typo and update swagger
none
=> release: draft release v0.2.2-alpha.1  

x/oracle/keeper/msg_server.go
This pr will fix the potential security issues:
+ Make sure the relayer reward is positive 
Fix the potential security issues
n/a
* fix the security issues
=> fix: fix the security issues

x/auth/tx/eip712.go
This pr is to add sorting of EIP712 msg types
Adding sorting can make types always consistent and as expected.
* add sorting of EIP712 msg types
=> fix: add sorting of EIP712 msg types

CHANGELOG.md
This release upgrades the reference cosmos-sdk to v0.47.3.
Please refer to the [changelogs of cosmos-sdk v0.47.3](https://github.com/cosmos/cosmos-sdk/blob/v0.47.3/CHANGELOG.md) for more details regarding the changes.
* [#220](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/220) feat: upgrade cosmos-sdk to v0.47.3
* [#214](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/214) chore: fix typo and update swagger
* [#219](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/219) fix: fix the security issues 
* [#218](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/218) fix: add sorting of EIP712 msg types
none
=> release: draft release for v0.2.2

client/utils.go
feat: allows for setting a custom http client when NewClientFromNode
=> feat: allows for setting a custom http client when NewClientFromNode

CHANGELOG.md
This release upgrades the reference cosmos-sdk to v0.47.3.
Please refer to the [changelogs of cosmos-sdk v0.47.3](https://github.com/cosmos/cosmos-sdk/blob/v0.47.3/CHANGELOG.md) for more details regarding the changes.
* [#220](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/220) feat: upgrade cosmos-sdk to v0.47.3
* [#214](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/214) chore: fix typo and update swagger
* [#219](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/219) fix: fix the security issues 
* [#218](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/218) fix: add sorting of EIP712 msg types
* [#224](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/224) feat: allows for setting a custom http client when NewClientFromNode 
* …
=> release: draft release for v0.2.3-alpha.1 (edit)

store/iavl/store.go
This pr will enable diff feature on iavl store, to track changed keys between versions.
Add feat 
NA
* add functions to iavl store
=> feat: enable diff on iavl store

store/rootmulti/store.go
This pr is to fix errors in `DeepCopy` and `DeepCopyAndCache` methods.
* add missing copy of transient store
=> fix: missing copy of transient store

api/cosmos/crosschain/v1/crosschain.pulsar.go, api/cosmos/crosschain/v1/tx.pulsar.go, api/cosmos/crosschain/v1/tx_grpc.pb.go, proto/cosmos/crosschain/v1/crosschain.proto, proto/cosmos/crosschain/v1/tx.proto, x/crosschain/keeper/keeper.go, x/crosschain/keeper/keeper_test.go, x/crosschain/keeper/msg_server.go, x/crosschain/module.go, x/crosschain/types/codec.go, x/crosschain/types/crosschain.pb.go, x/crosschain/types/msgs.go, x/crosschain/types/tx.pb.go, x/gashub/types/genesis.go
This pr will add `UpdateChannelPermissions` tx for crosschain module, so we can governance the channel permissions for the crosschain channels.
Add `UpdateChannelPermissions` tx for crosschain module.
n/a
* add UpdateChannelPermissions tx for crosschain module
=> feat: add UpdateChannelPermissions tx for crosschain module

x/auth/tx/eip712.go
This pr is to implement base64 encoding in EIP712
To keep consistency with js-sdk, we should adopt base64 encoding in EIP712.
* implement base64 encoding in EIP712
=> chore: implement base64 encoding in EIP712

CHANGELOG.md, go.mod, go.sum
This is a maintenance release.    
Features:
* [#247](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/247) feat: add UpdateChannelPermissions tx for crosschain module
Chores:
* [#246](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/246) chore: remove unused tools
* [#248](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/248) chore: implement base64 encoding in EIP712
* [#249](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/249) chore: adjust MsgSealObject gas to 120
none
=> release: draft release for v0.2.3-alpha.4

types/query/pagination.go, types/query/pagination_test.go
limit pagination to protect the node would not be Query DoS
* ...
=> fix: limit pagination to protect the node would not be Query DoS

baseapp/options.go, server/config/config.go, server/config/toml.go, server/start.go, server/util.go, types/events.go
This pr will allow node runners to define whether the node will emit events or not.
It is useful for nodes which do not want to emit any events.
new feat
```
Eventing = "everything"
Eventing = "nothing"
```
* new option in app.toml
=> feat: add option for disabling event emit

CHANGELOG.md
This pr drafts a new release for greenfield-cosmos-sdk.
This is a maintenance release.
Features:
* [#253](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/253) feat: add option for disabling event emit
Fix:
* [#252](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/252) fix: limit pagination to protect the node would not be Query DoS
Draft release
NA
* new feature
=> release: draft release for v0.2.3-alpha.5

baseapp/abci.go, baseapp/baseapp.go, baseapp/options.go, server/config/config.go, server/config/toml.go, server/start.go, server/util.go, types/context.go, types/query/pagination.go, x/auth/keeper/deterministic_test.go, x/auth/keeper/grpc_query.go, x/evidence/keeper/grpc_query.go
This pr will add a flag `enable-unsafe-query` to enable/disable heavy or unsafe queries.
Some queries are very heavy, we should have a flag to enable or disable such queries.
```
enable-unsafe-query = "true"
```
* new flag
=> feat: add flag to enable or disable heavy queries

CHANGELOG.md, go.mod, go.sum
This release includes 4 features and 1 bugfix.
Features:
* [#256](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/256) feat: add Nagqu fork name
* [#258](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/258) feat: add flag to enable or disable heavy queries
* [#263](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/263) feat: add MsgRenewGroupMember gas
* [#262](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/262) feat: add msg
Fix:  
* [#257](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/257) fix: add bls proof in proposal description
Documentation:  
* [#261](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/261) docs: prepare release 0.2.3
none
=> release: draft release for 0.2.4-alpha.1

CHANGELOG.md, baseapp/abci.go, baseapp/baseapp.go, baseapp/options.go, go.mod, go.sum, server/config/config.go, server/config/toml.go, server/start.go, server/util.go, types/context.go, types/query/pagination.go, x/auth/keeper/deterministic_test.go, x/auth/keeper/grpc_query.go, x/evidence/keeper/grpc_query.go, x/gashub/types/genesis.go, x/staking/client/cli/tx.go, x/upgrade/types/upgrade_config.go
This release includes 4 features and 1 bugfix.
Features:
* [#256](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/256) feat: add Nagqu fork name
* [#258](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/258) feat: add flag to enable or disable heavy queries
* [#263](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/263) feat: add MsgRenewGroupMember gas
* [#262](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/262) feat: add msg
Fix:  
* [#257](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/257) fix: add bls proof in proposal description
Documentation:  
* [#261](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/261) docs: prepare release 0.2.3
none
=> release: prepare release for 0.2.4-alpha.1

api/cosmos/crosschain/v1/tx.pulsar.go, api/cosmos/crosschain/v1/tx_grpc.pb.go, proto/cosmos/crosschain/v1/tx.proto, x/crosschain/keeper/keeper.go, x/crosschain/keeper/keeper_test.go, x/crosschain/keeper/msg_server.go, x/crosschain/module.go, x/crosschain/types/msgs.go, x/crosschain/types/tx.pb.go
In order to avoid cross-chain transfer due to insufficient funds in the module account, a message needs to be added so that funds can be increased.
token only mutable from gov
* crosschain
=> feat: make cross-chain token mintable

x/genutil/client/cli/gentx.go, x/staking/keeper/msg_server.go
allow validator delegator from Genesis to be other addresses
the delegator address is more privately key that may not be held by the deployer.
* staking
=> fix: allow validator delegator from Genesis to be other addresses

Makefile, tests/e2e/genutil/suite.go, x/auth/ante/ante_test.go, x/auth/ante/sigverify.go, x/auth/tx/decoder.go, x/genutil/client/cli/gentx.go
skip sig verification on genesis block
the `antehandler` will skip sig verification on the genesis block.
* genesis
=> feat: skip sig verification on genesis block

CHANGELOG.md, go.mod, go.sum, simapp/go.mod, simapp/go.sum, tests/go.mod, tests/go.sum
This release includes 5 new features.
Features:
* [#266](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/266) feat: implement cross-chain mechanism between op and greenfield
* [#267](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/267) feat: add method to access check state in app
* [#269](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/269) feat: track store r/w consume for enabling plain store
* [#270](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/270) feat: make cross-chain token mintable
* [#273](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/273) feat: skip sig verification on genesis block
Chores:
* [#268](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/268) chore: modify default gas
Please refer to the PRs for detailed information. …
=> release: draft release for v0.2.4-alpha.2

baseapp/abci.go, store/rootmulti/store.go
When using raw db store (no IAVL), the `Write()` function could write dirty data into the underlying store.
Thus we need to disable pre-deliver when raw db store is used.
Bug fix
NA
* disable pre-deliver
=> fix: disable pre deliver when raw db store is used

simapp/app.go, tests/integration/bank/keeper/keeper_test.go, x/bank/keeper/keeper_test.go, x/bank/keeper/msg_server.go, x/bank/module.go, x/bank/testutil/expected_keepers_mocks.go, x/bank/types/expected_keepers.go
This pr will restrict token transfers to payment accounts in greenfield. 
The payment accounts are derived from the owner account with an index, the tokens transferred to the payment accounts will lost since there is no private key for the accounts. This pr will restrict direct token transfer to the payment accounts to prevent token lost.
Restrict token transfers to payment accounts in greenfield. 
n/a
* restrict token transfers to payment accounts in greenfield
=> feat: restrict token transfers to payment accounts

x/auth/signing/verify.go
This pr is to make the description of the code comment more accurate
* no notable changes
=> chore: modify code comments in `VerifySignature`

CHANGELOG.md, go.mod, go.sum
This release includes all the changes in the v0.2.4 alpha versions and 2 new bugfixes.
Bugfixes:
* [#281](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/281) fix: disable pre deliver when raw db store is used
* [#287](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/287) fix: fix dependency security issues
Chores:
* [#289](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/289) chore: modify code comments in VerifySignature
none
=> release: draft release for v0.2.4  

CHANGELOG.md
This release includes 1 feature and 1 chore.
Features:
* [#277](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/277) feat: restrict token transfers to payment accounts
Chores:
* [#300](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/300) chore: add hardfork logic for Nagqu
NA
* changelogs
=> release: draft release for v0.2.5-alpha.1

CHANGELOG.md, simapp/app.go, store/types/gas.go, tests/integration/bank/keeper/keeper_test.go, types/context.go, types/upgrade.go, x/bank/keeper/keeper_test.go, x/bank/keeper/msg_server.go, x/bank/module.go, x/bank/testutil/expected_keepers_mocks.go, x/bank/types/expected_keepers.go, x/upgrade/keeper/keeper.go, x/upgrade/types/upgrade_config.go
This release includes 1 feature and 1 chore.
Features:
* [#277](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/277) feat: restrict token transfers to payment accounts
Chores:
* [#300](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/300) chore: add hardfork logic for Nagqu
NA
* changelogs
=> release: prepare release for v0.2.5-alpha.1

CHANGELOG.md, x/upgrade/types/upgrade_config.go
enable Nagqu hardfork to testnet
1694488975 (2023-9-12 03:22:55 AM +UTC) - block: 366648 ([greenfieldscan](https://greenfieldscan.com/block/366648))
1694761200 (2023-9-15 07:00:00 AM +UTC)
(1694761200 - 1694488975)/2.6 + 366648 ~= 471350
N/A
* upgrade
* changelog
=> feat: enable Nagqu hardfork to testnet

CHANGELOG.md
This release includes all the changes in the v0.2.5 alpha versions and 1 new feature.
Features:
* [#306](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/306) feat: enable Nagqu hardfork to testnet  
* [#277](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/277) feat: restrict token transfers to payment accounts
Chores:
* [#300](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/300) chore: add hardfork logic for Nagqu
none
=> release: draft release for v0.2.5

CHANGELOG.md, x/upgrade/types/upgrade_config.go
This release includes all the changes in the v0.2.5 alpha versions and 1 new feature.
Features:
* [#306](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/306) feat: enable Nagqu hardfork to testnet  
* [#277](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/277) feat: restrict token transfers to payment accounts
Chores:
* [#300](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/300) chore: add hardfork logic for Nagqu
none
=> release: prepare release for v0.2.5  

client/cmd.go, client/context.go, client/context_test.go, client/flags/flags.go, client/tx/factory.go, client/tx/tx.go, x/bank/client/cli/tx.go
This pr is to add a new flag to the cli
* add `FlagPrintEIP712MsgType` to support printing EIP712 types
=> feat: add `FlagPrintEIP712MsgType`

x/gov/keeper/crosschain.go, x/gov/types/crosschain.go, x/gov/types/errors.go, x/gov/types/v1/crosschain.go
Improve the validation of parameters.
Chore
NA
* parameter validations
=> chore: improve the validations of parameters

types/query/filtered_pagination.go
As some queries are using `GenericFilteredPaginate`, restrict the pagination limit to 100
* ...
=> fix: restrict pagination limit

CHANGELOG.md
This release caps the pagination limit for queries at 100 records if it exceeds the default pagination limit.
* [#315](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/315) fix: restrict pagination limit  
Please refer to individual PRs for detailed information.  
none
=> release: draft release for v0.2.6 alpha.2

CHANGELOG.md, types/query/filtered_pagination.go
This release caps the pagination limit for queries at 100 records if it exceeds the default pagination limit.
* [#315](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/315) fix: restrict pagination limit  
Please refer to individual PRs for detailed information.  
none
=> release: prepare release for v0.2.6-alpha.2

x/upgrade/keeper/keeper.go, x/upgrade/types/upgrade_config.go
add Nagqu fork to mainnet
n/a
n/a
* upgrade
=> feat: add Nagqu fork to mainnet

CHANGELOG.md
This release is the official release for the Greenfield mainnet.
This release includes 1 new feature.
* [#317](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/317) feat: add Nagqu fork to mainnet
NA
* add upgrade config
=> release: draft release for v1.0.0

CHANGELOG.md, client/tx/factory.go
This pr is to add support for multi msg when using `PrintEIP712MsgType` flag
* support multi msg for `PrintEIP712MsgType` flag
=> feat: support multi msg for `PrintEIP712MsgType` flag

CHANGELOG.md, client/tx/factory.go, x/upgrade/keeper/keeper.go, x/upgrade/types/upgrade_config.go
This release is the official release of greenfield-cosmos-sdk for the Greenfield mainnet.
This release includes 2 new features.
* [#317](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/317) feat: add Nagqu fork to mainnet
* [#323](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/323) feat: support multi msg for `PrintEIP712MsgType` flag
Release
NA
* add upgrade config
=> release: prepare release for v1.0.0

.github/workflows/gosec.yml, go.mod, go.sum, types/upgrade.go, x/upgrade/types/upgrade_config.go
This pr will introduce the `pampas` upgrade.
Introduce the `pampas` upgrade.
n/a
* introduce the `pampas` upgrade
=> feat: introduce the pampas upgrade

CHANGELOG.md
This pr will release v1.0.1, which is a maintenance release.
Bug fix
* [#338](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/338) fix: count total when pagination request is empty
NA
* change log
=> release: prepare release for v1.0.1

server/migrate_store.go, server/util.go, store/rootmulti/store.go
Add tool to migrate the stores, in mutli root store, from IAVL stores to DB stores.
For switch a full node to a fast node.
```
./build/bin/gnfd migrate-store --home ./deployment/localup/.local/dataseed1 
```
* new command
=> feat: add tool to migrate stores for fastnode

baseapp/baseapp.go, baseapp/msg_service_router.go, types/tx_msg.go, x/gov/keeper/proposal.go
Some validations are needed for different hardforks. 
`ValidateBasic` does not have information to detect hardforks.
`ValidateRuntime` can be used for validations with hardfork information. 
New feature
NA
* `ValidateRuntime` function
=> feat: add validation with context information

baseapp/abci.go, baseapp/ethrouter.go, go.mod, go.sum
This pr adds support for some json rpc queries:
+ `eth_gasPrice`
+ `eth_getCode`
+ `eth_estimateGas`
+ `eth_call`
+ `eth_getTransactionCount`
+ `eth_sendRawTransaction`
The handlers will only return dummy results since we will not support those queries. The reason for this pr is it will fix the error message complained by Metamask when transferring BNB to other accounts. It will tell users to use DCellar to transfer BNB instead of Metamask.
Add support for some json rpc queries and fix Metamask error message.
n/a
* add support for some json rpc queries
=> feat: add support for some json rpc queries

CHANGELOG.md
This release introduces the Pampas upgrade and 6 new features.  
Features:
* [#316](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/316) feat: add validation with context information
* [#321](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/321) feat: add tool to migrate stores for fastnode
* [#336](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/336) feat: introduce the pampas upgrade
* [#341](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/341) feat: add support for some json rpc queries
* [#353](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/353) feat: distinguish inturn relayer
* [#320](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/320) feat: add MsgRejectMigrateBucket
Please refer to individual PRs for detailed information.
Notable …
=> release: draft release for v1.1.0

client/keys/import.go, crypto/keyring/keyring.go
feat: support Secp256k1 private keys import
support Secp256k1 format private keys import via cmd
```bash
./build/bin/gnfd keys import testing 89319801b3f2d5cb... --home ./.local --secp256k1-private-key --keyring-backend test
./build/bin/gnfd keys list --home ./.local --keyring-backend test
```
* cmd
=> feat: support Secp256k1 format private keys import

x/upgrade/types/upgrade_config.go
Description
enable Nagqu hardfork to mainnet
Rationale
1700707216 (2023-11-23 02:40:16 AM +UTC)- block: 1634665 ([greenfieldscan](https://greenfieldscan.com/block/1634665))
1701673200 (2023-12-04 07:00:00 +UTC)
(1701673200 - 1700707216)/2.6 + 1634665 ~= `2,006,197`
Example
N/A
Changes
- upgrade
=> feat: enable Pampas hardfork to mainnet

CHANGELOG.md
This release introduces the Pampas upgrade to the mainnet. 
Features:
* [#360](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/360) feat: enable Pampas hardfork to mainnet
n/a
none
=> release: draft release for v1.1.1

CHANGELOG.md, types/upgrade.go, x/upgrade/types/upgrade_config.go
This release introduces the Pampas upgrade to the mainnet. 
Features:
* [#360](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/360) feat: enable Pampas hardfork to mainnet
n/a
none
=> release: prepare release for v1.1.1

math/int.go, math/int_test.go
feat: add xml marshal for Int type
When client uses golang/encoding/xml marshaler, it can't marshal cosmos Int type. So this PR will solve this problem.
```
func (s *intTestSuite) TestIntXmlMarshalRoundTrip() {
u1 := math.NewInt(256)
marshalResult, _ := xml.Marshal(u1)
u2 := math.Int{}
xml.Unmarshal(marshalResult, &u2)
s.Require().Equal(u1, u2)
}
```
* add xml marshal and unmarshal methods for Int type
* add ut
=> feat: add xml marshal for Int type

CHANGELOG.md, math/int.go, math/int_test.go, math/uint.go, math/uint_test.go, types/upgrade.go, x/upgrade/types/upgrade_config.go
This PR merge develop to master for v1.2.0
This release introduce the Manchurian upgrade to the testnet.
Chores:
* [#365](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/365) chore: add xml marshal for Int type
* [#364](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/364) chore: add xml marshal for UInt type
None
None
=> release: prepare for release v1.2.0

x/upgrade/types/upgrade_config.go
Description
enable `Manchurian` hardfork to testnet
Rationale
1702535422 (2023-12-14 06:30:22 +UTC)- block: 3223931 [greenfieldscan](https://testnet.greenfieldscan.com/block/3223931)
1703487600 (2023-12-25 07:00:00 +UTC)
(1703487600 - 1702535422)/2.6 + 3223931 ~= 3,590,153
Example
N/A
Changes
- upgrade
=> feat: enable Manchurian hardfork to testnet

x/upgrade/types/upgrade_config.go
This pr is to modify the `Manchurian` hardfork height of testnet
2023-12-25 07:07:38 +UTC- block: 3590185 [greenfieldscan](https://testnet.greenfieldscan.com/block/3590185)
2024-01-04 07:00:00 +UTC
(10 * 86400) / 2.6 + 3590259 ~= 3922485
Example
N/A
Changes
- modify the `Manchurian` hardfork height of testnet
=> feat: modify Manchurian hardfork height of testnet

CHANGELOG.md, x/upgrade/types/upgrade_config.go
Description
enable Manchurian hardfork to mainnet
Rationale
1704423531 (2024/1/05 02:58:51 AM +UTC)- block: 3055870 ([greenfieldscan](https://greenfieldscan.com/block/3055870))
1705388400 (2024/01/16 07:00:00 +UTC)
(1705388400 - 1704423531)/2.6 + 3055870 ~= `3,426,973`
Example
N/A
Changes
- upgrade
=> feat: introduce the Manchurian upgrade to the mainnet

x/upgrade/keeper/keeper.go
Fix upgrade initializers are not called when state sync.
If pre initializers are not called, it will lead to apphash mismatch issue. For example,
When doing migration, the to version (will be stored) is read from app.
```golang
toVersion := uint64(0)
if module, ok := module.(HasConsensusVersion); ok {
toVersion = module.ConsensusVersion()
}
...
updatedVM[moduleName] = toVersion
```
However, when doing state sync, it will not call all previous upgrade initializers, leading to `toVersion` is not correct.
NA
* upgrade handler
=> fix: module consensus version is not correctly set when upgrade after state sync

x/upgrade/keeper/keeper.go
Fix upgrade initializers are not called when state sync.
If pre initializers are not called, it will lead to apphash mismatch issue. For example,
When doing migration, the to version (will be stored) is read from app.
```golang
toVersion := uint64(0)
if module, ok := module.(HasConsensusVersion); ok {
toVersion = module.ConsensusVersion()
}
...
updatedVM[moduleName] = toVersion
```
However, when doing state sync, it will not call all previous upgrade initializers, leading to `toVersion` is not correct.
NA
* upgrade handler
Before fix:
After fix:
=> fix: module consensus version is not correctly set when upgrade after state sync 

x/upgrade/types/upgrade_config.go
this pr prepares for release v1.3.0 and config the Hardfork block height in Testnet and Mainnet. 
Height: 4512546.  Timestamp  1705894544 (2024-1-22 03:35:44 AM +UTC) https://testnet.greenfieldscan.com/block/4512546
1706770800 (2024/02/01 07:00:00 +UTC). 
**Target Hardfork height:**
(1706770800 - 1705894544)/2.6 + 4512546  ~= `4849568`
Height: 3623490. Timestamp 1705906178 (2024-1-22 06:49:38 AM +UTC) https://greenfieldscan.com/block/3623490
1708585200 (2024/2/22 7:00 am UTC). 
**Target Hardfork height:**
(1708585200 - 1705906178)/2.6 + 3623490  ~= `4653883`
=> release: prepare for release 1.3.0

CHANGELOG.md
just add change log for v1.4.0
Features:
* [#388](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/388) feat: introduce the Ural upgrade
BUGFIX
* [#391](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/391) fix: module consensus version is not correctly set when upgrade after state sync
None
None
=> doc:  add change log for release v1.4.0

CHANGELOG.md, x/upgrade/keeper/keeper.go
prepare for the v1.4.0 release
This release introduces the Ural upgrade.
Features:
* [#388](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/388) feat: introduce the Ural upgrade
BUGFIX
* [#391](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/391) fix: module consensus version is not correctly set when upgrade after state sync
None
None
=> release: prepare for the v1.4.0 release

go.mod, go.sum, x/upgrade/types/upgrade_config.go
update cometbft dependency version to v1.2.0, prepare for Ural upgrade
Height: 5491156.  Timestamp  1708487387 (2024-2-21 03:49:47 AM +UTC) https://testnet.greenfieldscan.com/block/5491156
1709190000 (2024/02/29 07:00:00 +UTC). 
**Target Hardfork height:**
(1709190000 - 1708487387)/2.6 + 5491156  ~= `5761391`
Height: 4611855. Timestamp 1708487620 (2024-2-21 03:53:40 AM +UTC) https://greenfieldscan.com/block/4611855
1710399600 (2024/3/14 7:00 am UTC). 
**Target Hardfork height:**
(1710399600 - 1708487620)/2.6 + 4611855  ~= `5347231`
* update cometbft dependency version to v1.2.0
* add ural upgrade plan
* ...
=> feat: prepare for release v1.4.0

types/upgrade.go, x/upgrade/types/upgrade_config.go
This pr will add upgrade `Serengeti`.
add upgrade `Serengeti`
n/a
* add upgrade `Serengeti`
=> feat: add upgrade Serengeti

tests/Makefile, x/upgrade/keeper/keeper.go
Sync blocks starting from genesis will fail on the first block.
```
{"level":"error","module":"server","module":"blockchain","err":"wrong Block.Header.LastResultsHash.  Expected 6908820926ED68A842B585BD1927F47F3853DC66EBA2A66AE899688848963151, got 007F040A8F62D6EEDD4B62FD11B145756DD5E6D47286280839DA676390F8F57C","time":"2024-03-07T15:07:17+08:00","message":"Error in validation"}
```
After `Nagqu`, the KV read gas will be set to 0 (https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/300).
However, "InitUpgraded" per block was added in `v1.4.0`(https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/391), if this happens before the `Nagqu` upgrade or at the same height, this will cause the gas reading to increase, causing `begin_block_extra_data`, ` end_block_extra_data` produces …
=> fix: sync failed from genesis

x/upgrade/types/upgrade_config.go
**Testnet:**
Height: 6152570.  Timestamp  1710299353 (13 March 2024 03:09:13)
1711522800 Wednesday, 27 March 2024 07:00:00
(1711522800 - 1710299353)/2.6 + 6152570  ~= `6623127`
**Mainnet:**
Height: 5303836. Timestamp 1710299621 (13 March 2024 03:13:41)
1712732400 (10 April 2024 07:00:00). 
(1712732400 - 1710299621)/2.6 + 5303836  ~= `6239520`
* ...
=> feat: set up Pawnee upgrade for Mainnet and Testnet

CHANGELOG.md, x/upgrade/types/upgrade_config.go
**Testnet**:
Current Height: 6983516.  Timestamp  1712458534
1713423600  18 April 2024 07:00:00
(1713423600 - 1712458534)/2.6 + 6983516  ~= **7354695**
**Mainnet**:
Current Height: 6126438. Timestamp 1712458199 
1714374000   29 April 2024 07:00:00
(1714374000 - 1712458199)/2.6 + 6126438  ~= **6863285**
* ...
=> feat: set up Serengeti upgrade for Mainnet and Testnet

CHANGELOG.md, go.mod, go.sum, x/upgrade/types/upgrade_config.go
1. config the Erdos hardfork height for testnet and mainnet. 
```
Testnet:
Current Height: 7715960.  Timestamp  1714362054
1715324400  10 May 2024 07:00:00.     UTC
(1715324400 - 1714362054)/2.6 + 7715960  ~= 8086093
Mainnet:
Height: 6858994. Timestamp 1714362187 
1716361200   22 May 2024 07:00:00
(1716361200 - 1714362187)/2.6 + 6858994  ~= 7627845
```
2. add change log 
* ...
=> docs: set up Erdos hardfork and  add change log 

x/upgrade/types/upgrade_config.go
set up hardfork height for Erdos
```
Testnet:
Current Height: 7753470.  Timestamp  1714459447
1715842800  16 May 2024 07:00:00.     UTC
(1715842800 - 1714459447)/2.6 + 7753470  ~= 8285529
Mainnet:
Height: 6897702. Timestamp 1714460240 
1716966000   29 May 2024 07:00:00
(1716966000 - 1714460240)/2.6 + 6897702  ~= 7861456
```
* ...
=> feat: set up hardfork height for Erdos

x/upgrade/types/upgrade_config.go
Testnet:
Current Height: 8099041.  Timestamp  1715359522
1715410800  11 May 2024 07:00:00.     UTC
AvgBlockTime: 2.9s
(1715410800 - 1715359522)/2.9 + 8099041  ~= 8116724
=> release: update the block height for erdos

CHANGELOG.md, types/upgrade.go, x/upgrade/types/upgrade_config.go
Testnet:
Current Height: 8518307. Timestamp 1716540978
1718694000 18 June 2024 07:00:00
AvgBlockTime: 2.5s
(1718694000 - 1716540978)/2.5 + 8518307 ~= 9379516
Mainnet:
Current Height: 7720024. Timestamp 1716540791
1719817200 1 July 2024 07:00:00
AvgBlockTime: 2.5s
(1719817200 - 1716540791)/2.5 + 7720024 ~= 9030588
N/A
N/A
* set up hardfork height and add CHANGELOG.md
=> feat: set up hardfork height and add CHANGELOG.md 

x/upgrade/types/upgrade_config.go
Testnet:
Current Height: 9115096. Timestamp 1718086884
1719298800 25 June 2024 07:00:00
(1719298800 - 1718086884)/2.6 + 9115096 ~= 9581218
Mainnet:
Current Height: 8335904. Timestamp 1718086984
1720422000 8 July 2024 07:00:00
AvgBlockTime: 2.5s
(1720422000 - 1718086984)/2.5 + 8335904 ~= 9269910
N/A
N/A
* set up hardfork height and add CHANGELOG.md
=> feat: update the block height for veld

CHANGELOG.md, types/upgrade.go, x/upgrade/types/upgrade_config.go
sync develop to master
N/A
N/A
* sync develop to master
=> release: sync develop to master

CHANGELOG.md, x/upgrade/types/upgrade_config.go
`Testnet`
Current Height: 10475935.  Timestamp  1721618012
1722409200  31 July 2024 07:00:00  UTC
(1722409200 - 1721618012)/2.6 + 10475935  ~= `10780238`
`Mainnet`
Height: 9744530. Timestamp 1721618206 
1723100400   08 Aug 2024 07:00:00
(1723100400 - 1721618206)/2.6 + 9744530  ~= `10314605`
The Greenfield Testnet is expected to have a scheduled hardfork upgrade named Mongolian
 at block height 10780238. The current block generation speed forecasts this to occur around 31 July 2024 07:00:00  UTC
The Greenfield Mainnet is expected to have a scheduled hardfork upgrade named Mongolian
 at block height 10314605. The current block generation speed forecasts this to occur around 08 Aug 2024 …
=> release: set up height for Mongolian hardfork

.github/workflows/test.yml, client/tx/factory.go, types/upgrade.go, x/auth/ante/sigverify.go, x/auth/client/cli/tx_multisign.go, x/auth/client/cli/validate_sigs.go, x/auth/migrations/legacytx/amino_signing.go, x/auth/signing/handler_map.go, x/auth/signing/sign_mode_handler.go, x/auth/signing/verify.go, x/auth/signing/verify_test.go, x/auth/tx/direct.go, x/auth/tx/direct_aux.go, x/auth/tx/eip712.go, x/auth/tx/legacy_amino_json.go, x/upgrade/types/upgrade_config.go
This pr is to fix the EIP712 signing issue and introduce a new hardfork Altai
* add new signing schema to fit metamask
=> feat: introduce the Altai upgrade

types/upgrade.go, x/upgrade/types/upgrade_config.go
Introduce a new hardfork - Savanna.
Add new hardfork.
Current Height: 14358790. Timestamp 1732158715
1733122800 02 December 2024 07:00:00 UTC
AvgBlockTime: 2.9s
(1733122800 - 1732158715)/2.9 + 14358790 ~= `14691233`
Current Height: 13939220. Timestamp 1732158632
1733986800 12 December 2024 07:00:00 UTC
AvgBlockTime: 2.51s
(1733986800 - 1732158632)/2.51 + 13939220 ~= `14667574`
The Greenfield Testnet is expected to have a scheduled hardfork upgrade named Savanna
at block height 14691233. The current block generation speed forecasts this to occur around 02 December 2024 07:00:00 UTC
The Greenfield Mainnet is expected to have a scheduled hardfork upgrade named Savanna
at block height 14667574. The …
=> feat: introduce the Savanna upgrade
