- CHANGELOG.md
This PR just add the changelog for release v0.2.1-alpha.1
prepare for new release on QA.
No
No
> docs: add change logs

- x/gashub/types/genesis.go
This pr adds msgUpdateGroupExtra.
to adapt change in pr https://github.com/bnb-chain/greenfield/pull/258
NA
* NA
> feat: add msg in gashub

- CHANGELOG.md
adds a change log
adds a change log
NA
* NA
> doc: add change log

- CHANGELOG.md
- baseapp/baseapp.go
- x/gashub/types/genesis.go
this release adds new msg type `msgUpdateGroupExtra` and fix block producing issue
Enable new msg type and fixing bug
NA
* https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/211
* https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/210
> release: prepare for release v0.2.1-alpha.2

- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
- proto/cosmos/gashub/v1beta1/query.proto
This pr is to fix typo and update swagger file
* add gashub module to swagger
> chore: fix typo and update swagger

- CHANGELOG.md
- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
- proto/cosmos/gashub/v1beta1/query.proto
This is a maintenance release.  
* [#214](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/214) chore: fix typo and update swagger
none
> release: prepare release v0.2.2-alpha.1

- client/utils.go
feat: optimize NewCustomClientFromNode
* ...
> feat: optimize NewCustomClientFromNode

- docs/docs/intro/00-overview.md
Perform wording change for binance related terms
none
none
none
> chore: bnb wording change

- go.mod
- go.sum
- x/staking/client/cli/tx.go
update greenfield-cometbft-db version(develop)
* ...
> chore: update greenfield-cometbft-db version

- x/gashub/types/genesis.go
adjust MsgSealObject gas to 120
* ...
> chore: adjust MsgSealObject gas to 120

- x/staking/client/cli/tx.go
Add bls proof in create validator proposal description
bls proof is newly added for creating validator, we need add this to the description
NA
* NA
> fix: add bls proof in proposal description

- CHANGELOG.md
- go.mod
- go.sum
docs: update change log to v0.2.3
* ...
> docs: update change log to v0.2.3

- CHANGELOG.md
- go.mod
- go.sum
docs: prepare release 0.2.3
* ...
> docs: prepare release 0.2.3

- x/upgrade/types/upgrade_config.go
add  `Nagqu` fork name for upcoming upgrading
* ...
> feat: add Nagqu fork name

- x/gashub/types/genesis.go
- x/upgrade/types/upgrade_config.go
add MsgRenewGroupMember gas
* genesis gas
> feat: add MsgRenewGroupMember gas

- x/gashub/types/genesis.go
> feat: add msg

- baseapp/baseapp.go
add method to access check state in app
app needs to access the check state sometimes, for example, to get the information of the last block.
NA
* NA
> feat: add method to access check state in app

- simapp/app.go
- tests/integration/bank/keeper/keeper_test.go
- x/bank/keeper/keeper_test.go
- x/bank/keeper/msg_server.go
- x/bank/module.go
- x/bank/testutil/expected_keepers_mocks.go
- x/bank/types/expected_keepers.go
Reverts bnb-chain/greenfield-cosmos-sdk#288
> Revert "Revert "feat: restrict token transfers to payment accounts""

- CHANGELOG.md
This release includes 1 new feature.
Features:
* [#310](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/310) feat: add FlagPrintEIP712MsgType  
Chores:
* [#312](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/312) chore: improve the validations of parameters
none
> release: draft release for v0.2.6-alpha.1

- CHANGELOG.md
- client/cmd.go
- client/context.go
- client/context_test.go
- client/flags/flags.go
- client/tx/factory.go
- client/tx/tx.go
- x/bank/client/cli/tx.go
- x/gov/keeper/crosschain.go
- x/gov/types/crosschain.go
- x/gov/types/errors.go
- x/gov/types/v1/crosschain.go
This release includes 1 new feature.
Features:
* [#310](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/310) feat: add FlagPrintEIP712MsgType  
Chores:
* [#312](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/312) chore: improve the validations of parameters
none
> release: prepare release for v0.2.6-alpha.1  

- x/gashub/types/genesis.go
add MsgRejectMigrateBucket for gas
* ...
> feat: add MsgRejectMigrateBucket

- types/upgrade.go
- x/upgrade/types/upgrade_config.go
This pr will introduce the `Eddystone` upgrade.
Introduce the `Eddystone` upgrade.
n/a
* introduce the `Eddystone` upgrade
> feat: introduce the Eddystone upgrade

- CHANGELOG.md
This PR is to prepare for new release v1.2.1
Update CHANGELOG.
N/A
no notable changes
> release: prepare for release v1.2.1

- CHANGELOG.md
- types/upgrade.go
- x/upgrade/types/upgrade_config.go
this PR introduces the `HulunbeierPatch` upgrade.
introduces the `HulunbeierPatch` upgrade.
* ...
> feat: introduces hulunbeier-patch upgrade

- types/upgrade.go
- x/upgrade/types/upgrade_config.go
This PR introduces the `Ural` upgrade.
Introduce the `Ural` upgrade.
NA
* NA
> feat: introduce the Ural upgrade

- CHANGELOG.md
- types/upgrade.go
- x/upgrade/types/upgrade_config.go
> release: sync develop to master

- types/upgrade.go
- x/upgrade/types/upgrade_config.go
introduce Pawnee upgrade
* ...
> feat: introduce Pawnee upgrade

- types/upgrade.go
- x/upgrade/types/upgrade_config.go
introduce the `Serengeti` upgrade
* ...
> release: prepare for release v1.6.0

- types/upgrade.go
- x/upgrade/types/upgrade_config.go
This pr is to introduce the Erdos upgrade
* add Erdos upgrade
> feat: introduce the Erdos upgrade

- types/upgrade.go
- x/upgrade/types/upgrade_config.go
This pr will add the erdos upgrade.
Add Erdos upgrade.
n/a
* add Erdos upgrade
> feat: add upgrade Erdos

- go.mod
- go.sum
- simapp/go.mod
- simapp/go.sum
- tests/go.mod
- tests/go.sum
> chore: deps security

- go.mod
- go.sum
- simapp/go.mod
- simapp/go.sum
- tests/go.mod
- tests/go.sum
> fix: deps security

- types/upgrade.go
- x/upgrade/types/upgrade_config.go
set up Mongolian upgrade for Mainnet and Testnet
> feat: set up Mongolian upgrade for Mainnet and Testnet

- CHANGELOG.md
- x/upgrade/types/upgrade_config.go
This pr is to set the height for Altai hardfork
* ...
> release: set up height for Altai hardfork

- .github/workflows/test.yml
- CHANGELOG.md
- client/tx/factory.go
- types/upgrade.go
- x/auth/ante/sigverify.go
- x/auth/client/cli/tx_multisign.go
- x/auth/client/cli/validate_sigs.go
- x/auth/migrations/legacytx/amino_signing.go
- x/auth/signing/handler_map.go
- x/auth/signing/sign_mode_handler.go
- x/auth/signing/verify.go
- x/auth/signing/verify_test.go
- x/auth/tx/direct.go
- x/auth/tx/direct_aux.go
- x/auth/tx/eip712.go
- x/auth/tx/legacy_amino_json.go
- x/upgrade/types/upgrade_config.go
Sync master to develop branch.
Sync branches.
NA
* new upgrdes
> chore: sync master to develop
